set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Build type" FORCE)
endif()

set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS Debug Release RelWithDebInfo MinSizeRel)

option(MS_ENABLE_WARNINGS_AS_ERRORS "Treat warnings as errors" ON)
option(MS_ENABLE_LTO "Enable link-time optimization" OFF)
option(MS_ENABLE_NATIVE_OPT "Enable -march=native for release-like builds" OFF)

if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
  if(MS_ENABLE_WARNINGS_AS_ERRORS)
    add_compile_options(-Werror)
  endif()

  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_compile_options(-O0 -g3)
  elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
    add_compile_options(-O3 -DNDEBUG)
  elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    add_compile_options(-O2 -g -DNDEBUG)
  elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
    add_compile_options(-Os -DNDEBUG)
  endif()

  if(MS_ENABLE_NATIVE_OPT)
    add_compile_options($<$<CONFIG:Release,RelWithDebInfo>:-march=native>)
  endif()
elseif(MSVC)
  add_compile_options(/W4)
  if(MS_ENABLE_WARNINGS_AS_ERRORS)
    add_compile_options(/WX)
  endif()
endif()

if(MS_ENABLE_LTO)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT ms_ipo_supported OUTPUT ms_ipo_error)
  if(ms_ipo_supported)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(WARNING "IPO/LTO requested but unavailable: ${ms_ipo_error}")
  endif()
endif()

message(STATUS "[platform] Compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "[platform] C++ standard: C++${CMAKE_CXX_STANDARD}")
message(STATUS "[platform] Build type: ${CMAKE_BUILD_TYPE}")
message(STATUS "[platform] Warnings as errors: ${MS_ENABLE_WARNINGS_AS_ERRORS}")
message(STATUS "[platform] LTO enabled: ${MS_ENABLE_LTO}")
