include_guard(GLOBAL)
include(FindPkgConfig)

set(MS_THIRD_PARTY_LINK_TARGETS "")
set(MS_THIRD_PARTY_LIBRARIES "")
set(MS_THIRD_PARTY_INCLUDE_DIRS "")
set(MS_THIRD_PARTY_REPORT_LINES "")

function(ms_record_dependency dep source version include_dir)
  list(APPEND MS_THIRD_PARTY_REPORT_LINES "[deps] ${dep}: source=${source}, version=${version}, include=${include_dir}")
  set(MS_THIRD_PARTY_REPORT_LINES "${MS_THIRD_PARTY_REPORT_LINES}" PARENT_SCOPE)
endfunction()

# protobuf
find_package(Protobuf CONFIG QUIET)
if(TARGET protobuf::libprotobuf)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS protobuf::libprotobuf)
  get_target_property(_protobuf_inc protobuf::libprotobuf INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("protobuf" "cmake-config" "${Protobuf_VERSION}" "${_protobuf_inc}")
else()
  find_package(Protobuf QUIET MODULE)
endif()

if(TARGET protobuf::libprotobuf)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS protobuf::libprotobuf)
  get_target_property(_protobuf_inc protobuf::libprotobuf INTERFACE_INCLUDE_DIRECTORIES)
  if(NOT _protobuf_inc)
    set(_protobuf_inc "${Protobuf_INCLUDE_DIRS}")
  endif()
  ms_record_dependency("protobuf" "cmake-target" "${Protobuf_VERSION}" "${_protobuf_inc}")
elseif(Protobuf_FOUND)
  list(APPEND MS_THIRD_PARTY_LIBRARIES ${Protobuf_LIBRARIES})
  list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${Protobuf_INCLUDE_DIRS})
  ms_record_dependency("protobuf" "cmake-module" "${Protobuf_VERSION}" "${Protobuf_INCLUDE_DIRS}")
else()
  pkg_check_modules(PROTOBUF QUIET protobuf)
  if(PROTOBUF_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${PROTOBUF_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${PROTOBUF_INCLUDE_DIRS})
    ms_record_dependency("protobuf" "pkg-config" "${PROTOBUF_VERSION}" "${PROTOBUF_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: protobuf")
  endif()
endif()

# gRPC
find_package(gRPC CONFIG QUIET)
if(TARGET gRPC::grpc++)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS gRPC::grpc++)
  get_target_property(_grpc_inc gRPC::grpc++ INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("gRPC" "cmake-config" "${gRPC_VERSION}" "${_grpc_inc}")
else()
  pkg_check_modules(GRPCPP QUIET grpc++)
  if(GRPCPP_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${GRPCPP_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${GRPCPP_INCLUDE_DIRS})
    ms_record_dependency("gRPC" "pkg-config" "${GRPCPP_VERSION}" "${GRPCPP_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: gRPC")
  endif()
endif()

# Abseil
find_package(absl CONFIG QUIET)
if(TARGET absl::strings)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS absl::strings)
  get_target_property(_absl_inc absl::strings INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("absl" "cmake-config" "unknown" "${_absl_inc}")
endif()

# gflags
find_package(gflags CONFIG QUIET)
if(TARGET gflags::gflags)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS gflags::gflags)
  get_target_property(_gflags_inc gflags::gflags INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("gflags" "cmake-config" "unknown" "${_gflags_inc}")
elseif(TARGET gflags)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS gflags)
  get_target_property(_gflags_inc gflags INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("gflags" "cmake-config" "unknown" "${_gflags_inc}")
else()
  find_package(gflags QUIET MODULE)
endif()

if(TARGET gflags::gflags)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS gflags::gflags)
  get_target_property(_gflags_inc gflags::gflags INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("gflags" "cmake-module" "unknown" "${_gflags_inc}")
elseif(TARGET gflags)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS gflags)
  get_target_property(_gflags_inc gflags INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("gflags" "cmake-module" "unknown" "${_gflags_inc}")
elseif(gflags_FOUND)
  list(APPEND MS_THIRD_PARTY_LIBRARIES ${GFLAGS_LIBRARIES})
  list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${GFLAGS_INCLUDE_DIRS})
  ms_record_dependency("gflags" "cmake-module" "${gflags_VERSION}" "${GFLAGS_INCLUDE_DIRS}")
else()
  pkg_check_modules(GFLAGS QUIET gflags)
  if(GFLAGS_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${GFLAGS_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${GFLAGS_INCLUDE_DIRS})
    ms_record_dependency("gflags" "pkg-config" "${GFLAGS_VERSION}" "${GFLAGS_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: gflags")
  endif()
endif()

# glog
find_package(glog CONFIG QUIET)
if(TARGET glog::glog)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS glog::glog)
  get_target_property(_glog_inc glog::glog INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("glog" "cmake-config" "${glog_VERSION}" "${_glog_inc}")
elseif(TARGET glog)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS glog)
  get_target_property(_glog_inc glog INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("glog" "cmake-target" "unknown" "${_glog_inc}")
else()
  find_package(Glog QUIET MODULE)
  if(TARGET Glog::glog)
    list(APPEND MS_THIRD_PARTY_LINK_TARGETS Glog::glog)
    get_target_property(_glog_inc Glog::glog INTERFACE_INCLUDE_DIRECTORIES)
    ms_record_dependency("glog" "cmake-module" "${GLOG_VERSION_STRING}" "${_glog_inc}")
  elseif(GLOG_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${GLOG_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${GLOG_INCLUDE_DIRS})
    ms_record_dependency("glog" "cmake-module" "${GLOG_VERSION_STRING}" "${GLOG_INCLUDE_DIRS}")
  else()
    pkg_check_modules(GLOG_PC QUIET libglog)
    if(GLOG_PC_FOUND)
      list(APPEND MS_THIRD_PARTY_LIBRARIES ${GLOG_PC_LINK_LIBRARIES})
      list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${GLOG_PC_INCLUDE_DIRS})
      ms_record_dependency("glog" "pkg-config" "${GLOG_PC_VERSION}" "${GLOG_PC_INCLUDE_DIRS}")
    else()
      message(FATAL_ERROR "Required dependency not found: glog")
    endif()
  endif()
endif()

# Boost
find_package(Boost QUIET REQUIRED COMPONENTS filesystem system thread)
if(TARGET Boost::filesystem)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS Boost::filesystem Boost::system Boost::thread)
  ms_record_dependency("Boost" "cmake-config" "${Boost_VERSION}" "${Boost_INCLUDE_DIRS}")
else()
  list(APPEND MS_THIRD_PARTY_LIBRARIES ${Boost_LIBRARIES})
  list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})
  ms_record_dependency("Boost" "cmake-module" "${Boost_VERSION}" "${Boost_INCLUDE_DIRS}")
endif()

# OpenCV
find_package(OpenCV QUIET CONFIG COMPONENTS core imgproc imgcodecs)
if(OpenCV_FOUND)
  list(APPEND MS_THIRD_PARTY_LIBRARIES ${OpenCV_LIBS})
  list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${OpenCV_INCLUDE_DIRS})
  ms_record_dependency("OpenCV" "cmake-config" "${OpenCV_VERSION}" "${OpenCV_INCLUDE_DIRS}")
else()
  pkg_check_modules(OPENCV QUIET opencv4)
  if(NOT OPENCV_FOUND)
    pkg_check_modules(OPENCV QUIET opencv)
  endif()
  if(OPENCV_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${OPENCV_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${OPENCV_INCLUDE_DIRS})
    ms_record_dependency("OpenCV" "pkg-config" "${OPENCV_VERSION}" "${OPENCV_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: OpenCV")
  endif()
endif()

# ONNX Runtime
set(
  ONNXRUNTIME_ROOT
  "/home/honeywell/lib/onnxruntime-linux-x64-gpu-1.21.0"
  CACHE PATH "Root directory of ONNX Runtime installation"
)
set(_onnxruntime_hint_paths
    "${ONNXRUNTIME_ROOT}"
    "${ONNXRUNTIME_ROOT}/lib/cmake/onnxruntime"
    "${ONNXRUNTIME_ROOT}/lib64/cmake/onnxruntime")
set(_onnxruntime_config_file "${ONNXRUNTIME_ROOT}/lib/cmake/onnxruntime/onnxruntimeConfig.cmake")
file(GLOB _onnxruntime_lib64_candidates "${ONNXRUNTIME_ROOT}/lib64/libonnxruntime.so*")
if(EXISTS "${_onnxruntime_config_file}" AND _onnxruntime_lib64_candidates)
  find_package(onnxruntime CONFIG QUIET HINTS ${_onnxruntime_hint_paths})
endif()
if(TARGET onnxruntime::onnxruntime)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS onnxruntime::onnxruntime)
  get_target_property(_onnxruntime_inc onnxruntime::onnxruntime INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("onnxruntime" "cmake-config" "unknown" "${_onnxruntime_inc}")
elseif(TARGET onnxruntime)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS onnxruntime)
  get_target_property(_onnxruntime_inc onnxruntime INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("onnxruntime" "cmake-config" "unknown" "${_onnxruntime_inc}")
else()
  find_path(
    ONNXRUNTIME_INCLUDE_DIR
    NAMES onnxruntime_c_api.h
    HINTS "${ONNXRUNTIME_ROOT}/include"
  )
  find_library(
    ONNXRUNTIME_LIBRARY
    NAMES onnxruntime
    HINTS "${ONNXRUNTIME_ROOT}/lib" "${ONNXRUNTIME_ROOT}/lib64"
  )
  if(ONNXRUNTIME_INCLUDE_DIR AND ONNXRUNTIME_LIBRARY)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${ONNXRUNTIME_LIBRARY})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${ONNXRUNTIME_INCLUDE_DIR})
    ms_record_dependency("onnxruntime" "manual-root" "1.21.0" "${ONNXRUNTIME_INCLUDE_DIR}")
  else()
    pkg_check_modules(ONNXRUNTIME QUIET onnxruntime)
    if(ONNXRUNTIME_FOUND)
      list(APPEND MS_THIRD_PARTY_LIBRARIES ${ONNXRUNTIME_LINK_LIBRARIES})
      list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${ONNXRUNTIME_INCLUDE_DIRS})
      ms_record_dependency("onnxruntime" "pkg-config" "${ONNXRUNTIME_VERSION}" "${ONNXRUNTIME_INCLUDE_DIRS}")
    else()
      message(FATAL_ERROR "Required dependency not found: onnxruntime")
    endif()
  endif()
endif()

# MySQL client
find_package(MySQLClient QUIET MODULE)
if(TARGET MySQLClient::MySQLClient)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS MySQLClient::MySQLClient)
  ms_record_dependency("MySQLClient" "custom-find-module" "unknown" "${MySQLClient_INCLUDE_DIRS}")
else()
  pkg_check_modules(MYSQLCLIENT QUIET mysqlclient)
  if(MYSQLCLIENT_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${MYSQLCLIENT_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${MYSQLCLIENT_INCLUDE_DIRS})
    ms_record_dependency("MySQLClient" "pkg-config" "${MYSQLCLIENT_VERSION}" "${MYSQLCLIENT_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: MySQLClient")
  endif()
endif()

# RabbitMQ C client
find_package(RabbitMQC QUIET MODULE)
if(TARGET RabbitMQC::RabbitMQC)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS RabbitMQC::RabbitMQC)
  ms_record_dependency("RabbitMQC" "custom-find-module" "unknown" "${RabbitMQC_INCLUDE_DIRS}")
else()
  pkg_check_modules(RABBITMQC QUIET rabbitmq)
  if(NOT RABBITMQC_FOUND)
    pkg_check_modules(RABBITMQC QUIET rabbitmq-c)
  endif()
  if(RABBITMQC_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${RABBITMQC_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${RABBITMQC_INCLUDE_DIRS})
    ms_record_dependency("RabbitMQC" "pkg-config" "${RABBITMQC_VERSION}" "${RABBITMQC_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: RabbitMQC")
  endif()
endif()

# OSS SDK
find_package(OSSSDK QUIET MODULE)
if(TARGET OSSSDK::OSSSDK)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS OSSSDK::OSSSDK)
  ms_record_dependency("OSSSDK" "custom-find-module" "unknown" "${OSSSDK_INCLUDE_DIRS}")
else()
  pkg_check_modules(OSSSDK QUIET alibabacloud-oss-cpp-sdk)
  if(NOT OSSSDK_FOUND)
    pkg_check_modules(OSSSDK QUIET oss-cpp-sdk)
  endif()
  if(OSSSDK_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${OSSSDK_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${OSSSDK_INCLUDE_DIRS})
    ms_record_dependency("OSSSDK" "pkg-config" "${OSSSDK_VERSION}" "${OSSSDK_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: OSSSDK")
  endif()
endif()

# Moduo (muduo)
find_package(Moduo CONFIG QUIET)
if(TARGET Moduo::Moduo)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS Moduo::Moduo)
  get_target_property(_moduo_inc Moduo::Moduo INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("moduo" "cmake-config" "unknown" "${_moduo_inc}")
else()
  find_package(Moduo QUIET MODULE)
endif()

if(TARGET Moduo::Moduo)
  list(APPEND MS_THIRD_PARTY_LINK_TARGETS Moduo::Moduo)
  get_target_property(_moduo_inc Moduo::Moduo INTERFACE_INCLUDE_DIRECTORIES)
  ms_record_dependency("moduo" "cmake-module" "unknown" "${_moduo_inc}")
else()
  pkg_check_modules(MODUO QUIET moduo)
  if(NOT MODUO_FOUND)
    pkg_check_modules(MODUO QUIET muduo)
  endif()
  if(MODUO_FOUND)
    list(APPEND MS_THIRD_PARTY_LIBRARIES ${MODUO_LINK_LIBRARIES})
    list(APPEND MS_THIRD_PARTY_INCLUDE_DIRS ${MODUO_INCLUDE_DIRS})
    ms_record_dependency("moduo" "pkg-config" "${MODUO_VERSION}" "${MODUO_INCLUDE_DIRS}")
  else()
    message(FATAL_ERROR "Required dependency not found: moduo")
  endif()
endif()

list(REMOVE_DUPLICATES MS_THIRD_PARTY_LIBRARIES)
list(REMOVE_DUPLICATES MS_THIRD_PARTY_INCLUDE_DIRS)

if(NOT TARGET thirdparty_deps)
  add_library(thirdparty_deps INTERFACE)
  add_library(thirdparty::deps ALIAS thirdparty_deps)
endif()

target_include_directories(thirdparty_deps INTERFACE ${MS_THIRD_PARTY_INCLUDE_DIRS})
target_link_libraries(thirdparty_deps INTERFACE ${MS_THIRD_PARTY_LINK_TARGETS} ${MS_THIRD_PARTY_LIBRARIES})

foreach(_line IN LISTS MS_THIRD_PARTY_REPORT_LINES)
  message(STATUS "${_line}")
endforeach()

set(MS_THIRD_PARTY_INCLUDE_DIRS "${MS_THIRD_PARTY_INCLUDE_DIRS}" CACHE INTERNAL "Resolved third-party include dirs")
set(MS_THIRD_PARTY_LINK_TARGETS "${MS_THIRD_PARTY_LINK_TARGETS}" CACHE INTERNAL "Resolved third-party link targets")
set(MS_THIRD_PARTY_LIBRARIES "${MS_THIRD_PARTY_LIBRARIES}" CACHE INTERNAL "Resolved third-party libraries")
